### ISSUE TITLE
Images and content reloading when running locally

### ISSUE THREAD

**Issue by urosht** [kromiii/notion-to-slides#6]
Hi, great project you have there, wanted to provide some feedback on my usage

# What
- Images and text keep reloading and causing a "blink" when running locally

# How to Reproduce
- Run locally with `npm run start....` and use a Notion page that has an image pasted from the clipboard

# Additional Information
- Left a video to see the actual behavior.

https://github.com/user-attachments/assets/ba70d305-219d-403e-b3ff-05b71ebec7ba

**Comment by kromiii** [comment]
Thanks for your feedback! I removed the auto reload function, which caused the issue. Please update the code and try again.
